spring:
  application:
    name: ec2-test-app
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  jackson:  #JSON 변환 라이브러리 타임존
    time-zone:
      Asia/Seoul
  datasource:
    url: jdbc:mysql://localhost:3306/ec2-testdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: INFO
    com.example.ec2testapp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %"
server:
  port: 8080
debug: true
